/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CryptoGate.Client;
using CryptoGate.Model;

namespace CryptoGate.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Merchant plan, usage and limits
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetAccount200Response</returns>
        GetAccount200Response GetAccount();

        /// <summary>
        /// Merchant plan, usage and limits
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetAccount200Response</returns>
        ApiResponse<GetAccount200Response> GetAccountWithHttpInfo();
        /// <summary>
        /// Merchant transaction analytics
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetStats200Response</returns>
        GetStats200Response GetStats();

        /// <summary>
        /// Merchant transaction analytics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetStats200Response</returns>
        ApiResponse<GetStats200Response> GetStatsWithHttpInfo();
        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement)
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListBalances200Response</returns>
        ListBalances200Response ListBalances();

        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListBalances200Response</returns>
        ApiResponse<ListBalances200Response> ListBalancesWithHttpInfo();
        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant)
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <returns>ListInvoices200Response</returns>
        ListInvoices200Response ListInvoices(int? limit = default(int?), int? offset = default(int?));

        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <returns>ApiResponse of ListInvoices200Response</returns>
        ApiResponse<ListInvoices200Response> ListInvoicesWithHttpInfo(int? limit = default(int?), int? offset = default(int?));
        /// <summary>
        /// Plan catalogue and pricing
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListPlans200Response</returns>
        ListPlans200Response ListPlans();

        /// <summary>
        /// Plan catalogue and pricing
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListPlans200Response</returns>
        ApiResponse<ListPlans200Response> ListPlansWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Merchant plan, usage and limits
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccount200Response</returns>
        System.Threading.Tasks.Task<GetAccount200Response> GetAccountAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Merchant plan, usage and limits
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccount200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetAccount200Response>> GetAccountWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Merchant transaction analytics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStats200Response</returns>
        System.Threading.Tasks.Task<GetStats200Response> GetStatsAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Merchant transaction analytics
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStats200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStats200Response>> GetStatsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListBalances200Response</returns>
        System.Threading.Tasks.Task<ListBalances200Response> ListBalancesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListBalances200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListBalances200Response>> ListBalancesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListInvoices200Response</returns>
        System.Threading.Tasks.Task<ListInvoices200Response> ListInvoicesAsync(int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListInvoices200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListInvoices200Response>> ListInvoicesWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Plan catalogue and pricing
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPlans200Response</returns>
        System.Threading.Tasks.Task<ListPlans200Response> ListPlansAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Plan catalogue and pricing
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPlans200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListPlans200Response>> ListPlansWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApi : IAccountApiSync, IAccountApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountApi : IDisposable, IAccountApi
    {
        private CryptoGate.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AccountApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AccountApi(string basePath)
        {
            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                new CryptoGate.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AccountApi(CryptoGate.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                new CryptoGate.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountApi(HttpClient client, CryptoGate.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AccountApi(CryptoGate.Client.ISynchronousClient client, CryptoGate.Client.IAsynchronousClient asyncClient, CryptoGate.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CryptoGate.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CryptoGate.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CryptoGate.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CryptoGate.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CryptoGate.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Merchant plan, usage and limits 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetAccount200Response</returns>
        public GetAccount200Response GetAccount()
        {
            CryptoGate.Client.ApiResponse<GetAccount200Response> localVarResponse = GetAccountWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merchant plan, usage and limits 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetAccount200Response</returns>
        public CryptoGate.Client.ApiResponse<GetAccount200Response> GetAccountWithHttpInfo()
        {
            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetAccount200Response>("/account", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Merchant plan, usage and limits 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccount200Response</returns>
        public async System.Threading.Tasks.Task<GetAccount200Response> GetAccountAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            CryptoGate.Client.ApiResponse<GetAccount200Response> localVarResponse = await GetAccountWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merchant plan, usage and limits 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccount200Response)</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<GetAccount200Response>> GetAccountWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetAccount200Response>("/account", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccount", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Merchant transaction analytics 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetStats200Response</returns>
        public GetStats200Response GetStats()
        {
            CryptoGate.Client.ApiResponse<GetStats200Response> localVarResponse = GetStatsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merchant transaction analytics 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetStats200Response</returns>
        public CryptoGate.Client.ApiResponse<GetStats200Response> GetStatsWithHttpInfo()
        {
            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStats200Response>("/stats", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStats", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Merchant transaction analytics 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStats200Response</returns>
        public async System.Threading.Tasks.Task<GetStats200Response> GetStatsAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            CryptoGate.Client.ApiResponse<GetStats200Response> localVarResponse = await GetStatsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merchant transaction analytics 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStats200Response)</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<GetStats200Response>> GetStatsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStats200Response>("/stats", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStats", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListBalances200Response</returns>
        public ListBalances200Response ListBalances()
        {
            CryptoGate.Client.ApiResponse<ListBalances200Response> localVarResponse = ListBalancesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListBalances200Response</returns>
        public CryptoGate.Client.ApiResponse<ListBalances200Response> ListBalancesWithHttpInfo()
        {
            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListBalances200Response>("/balances", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBalances", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListBalances200Response</returns>
        public async System.Threading.Tasks.Task<ListBalances200Response> ListBalancesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            CryptoGate.Client.ApiResponse<ListBalances200Response> localVarResponse = await ListBalancesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// On-platform balances (for overage/top-up; NOT crypto settlement) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListBalances200Response)</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<ListBalances200Response>> ListBalancesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListBalances200Response>("/balances", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBalances", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <returns>ListInvoices200Response</returns>
        public ListInvoices200Response ListInvoices(int? limit = default(int?), int? offset = default(int?))
        {
            CryptoGate.Client.ApiResponse<ListInvoices200Response> localVarResponse = ListInvoicesWithHttpInfo(limit, offset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <returns>ApiResponse of ListInvoices200Response</returns>
        public CryptoGate.Client.ApiResponse<ListInvoices200Response> ListInvoicesWithHttpInfo(int? limit = default(int?), int? offset = default(int?))
        {
            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListInvoices200Response>("/invoices", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListInvoices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListInvoices200Response</returns>
        public async System.Threading.Tasks.Task<ListInvoices200Response> ListInvoicesAsync(int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            CryptoGate.Client.ApiResponse<ListInvoices200Response> localVarResponse = await ListInvoicesWithHttpInfoAsync(limit, offset, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// CryptoGate billing invoices (platform ↔ merchant) 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListInvoices200Response)</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<ListInvoices200Response>> ListInvoicesWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListInvoices200Response>("/invoices", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListInvoices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Plan catalogue and pricing 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListPlans200Response</returns>
        public ListPlans200Response ListPlans()
        {
            CryptoGate.Client.ApiResponse<ListPlans200Response> localVarResponse = ListPlansWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Plan catalogue and pricing 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListPlans200Response</returns>
        public CryptoGate.Client.ApiResponse<ListPlans200Response> ListPlansWithHttpInfo()
        {
            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListPlans200Response>("/plans", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPlans", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Plan catalogue and pricing 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPlans200Response</returns>
        public async System.Threading.Tasks.Task<ListPlans200Response> ListPlansAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            CryptoGate.Client.ApiResponse<ListPlans200Response> localVarResponse = await ListPlansWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Plan catalogue and pricing 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPlans200Response)</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<ListPlans200Response>> ListPlansWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListPlans200Response>("/plans", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPlans", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
