/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CryptoGate.Client;
using CryptoGate.Model;

namespace CryptoGate.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL
        /// </summary>
        /// <remarks>
        /// Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <returns></returns>
        void PaymentWebhook(WebhookPayload? webhookPayload = default(WebhookPayload?));

        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL
        /// </summary>
        /// <remarks>
        /// Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PaymentWebhookWithHttpInfo(WebhookPayload? webhookPayload = default(WebhookPayload?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL
        /// </summary>
        /// <remarks>
        /// Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PaymentWebhookAsync(WebhookPayload? webhookPayload = default(WebhookPayload?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL
        /// </summary>
        /// <remarks>
        /// Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PaymentWebhookWithHttpInfoAsync(WebhookPayload? webhookPayload = default(WebhookPayload?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IDefaultApiSync, IDefaultApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDisposable, IDefaultApi
    {
        private CryptoGate.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DefaultApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DefaultApi(string basePath)
        {
            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                new CryptoGate.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DefaultApi(CryptoGate.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                new CryptoGate.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, CryptoGate.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DefaultApi(CryptoGate.Client.ISynchronousClient client, CryptoGate.Client.IAsynchronousClient asyncClient, CryptoGate.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CryptoGate.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CryptoGate.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CryptoGate.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CryptoGate.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CryptoGate.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <returns></returns>
        public void PaymentWebhook(WebhookPayload? webhookPayload = default(WebhookPayload?))
        {
            PaymentWebhookWithHttpInfo(webhookPayload);
        }

        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CryptoGate.Client.ApiResponse<Object> PaymentWebhookWithHttpInfo(WebhookPayload? webhookPayload = default(WebhookPayload?))
        {
            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = webhookPayload;

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/paymentEvent", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PaymentWebhook", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PaymentWebhookAsync(WebhookPayload? webhookPayload = default(WebhookPayload?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await PaymentWebhookWithHttpInfoAsync(webhookPayload, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Payment lifecycle event delivered to the merchant&#39;s webhook URL Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="webhookPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<Object>> PaymentWebhookWithHttpInfoAsync(WebhookPayload? webhookPayload = default(WebhookPayload?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = webhookPayload;

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/paymentEvent", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PaymentWebhook", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
