/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using CryptoGate.Client;
using CryptoGate.Model;

namespace CryptoGate.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISystemApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// API health check
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetHealth200Response</returns>
        GetHealth200Response GetHealth();

        /// <summary>
        /// API health check
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetHealth200Response</returns>
        ApiResponse<GetHealth200Response> GetHealthWithHttpInfo();
        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key)
        /// </summary>
        /// <remarks>
        /// Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <returns></returns>
        void HostedCheckoutRedirect(string pk, string amount, CryptoSymbol crypto, string? link = default(string?));

        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key)
        /// </summary>
        /// <remarks>
        /// Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> HostedCheckoutRedirectWithHttpInfo(string pk, string amount, CryptoSymbol crypto, string? link = default(string?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISystemApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// API health check
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetHealth200Response</returns>
        System.Threading.Tasks.Task<GetHealth200Response> GetHealthAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// API health check
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetHealth200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetHealth200Response>> GetHealthWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key)
        /// </summary>
        /// <remarks>
        /// Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task HostedCheckoutRedirectAsync(string pk, string amount, CryptoSymbol crypto, string? link = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key)
        /// </summary>
        /// <remarks>
        /// Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </remarks>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> HostedCheckoutRedirectWithHttpInfoAsync(string pk, string amount, CryptoSymbol crypto, string? link = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISystemApi : ISystemApiSync, ISystemApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SystemApi : IDisposable, ISystemApi
    {
        private CryptoGate.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public SystemApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SystemApi(string basePath)
        {
            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                new CryptoGate.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SystemApi(CryptoGate.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SystemApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SystemApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                new CryptoGate.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SystemApi(HttpClient client, CryptoGate.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = CryptoGate.Client.Configuration.MergeConfigurations(
                CryptoGate.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new CryptoGate.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SystemApi(CryptoGate.Client.ISynchronousClient client, CryptoGate.Client.IAsynchronousClient asyncClient, CryptoGate.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = CryptoGate.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public CryptoGate.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public CryptoGate.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public CryptoGate.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CryptoGate.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CryptoGate.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// API health check 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetHealth200Response</returns>
        public GetHealth200Response GetHealth()
        {
            CryptoGate.Client.ApiResponse<GetHealth200Response> localVarResponse = GetHealthWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// API health check 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetHealth200Response</returns>
        public CryptoGate.Client.ApiResponse<GetHealth200Response> GetHealthWithHttpInfo()
        {
            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<GetHealth200Response>("/health", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetHealth", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// API health check 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetHealth200Response</returns>
        public async System.Threading.Tasks.Task<GetHealth200Response> GetHealthAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            CryptoGate.Client.ApiResponse<GetHealth200Response> localVarResponse = await GetHealthWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// API health check 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetHealth200Response)</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<GetHealth200Response>> GetHealthWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetHealth200Response>("/health", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetHealth", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key) Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <returns></returns>
        public void HostedCheckoutRedirect(string pk, string amount, CryptoSymbol crypto, string? link = default(string?))
        {
            HostedCheckoutRedirectWithHttpInfo(pk, amount, crypto, link);
        }

        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key) Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public CryptoGate.Client.ApiResponse<Object> HostedCheckoutRedirectWithHttpInfo(string pk, string amount, CryptoSymbol crypto, string? link = default(string?))
        {
            // verify the required parameter 'pk' is set
            if (pk == null)
                throw new CryptoGate.Client.ApiException(400, "Missing required parameter 'pk' when calling SystemApi->HostedCheckoutRedirect");

            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new CryptoGate.Client.ApiException(400, "Missing required parameter 'amount' when calling SystemApi->HostedCheckoutRedirect");

            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "pk", pk));
            localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "amount", amount));
            localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "crypto", crypto));
            if (link != null)
            {
                localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "link", link));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/pay", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HostedCheckoutRedirect", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key) Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task HostedCheckoutRedirectAsync(string pk, string amount, CryptoSymbol crypto, string? link = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await HostedCheckoutRedirectWithHttpInfoAsync(pk, amount, crypto, link, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Hosted-checkout redirect (browser flow, publishable key) Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
        /// </summary>
        /// <exception cref="CryptoGate.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pk">Publishable key, pk_live_… / pk_test_…</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent).</param>
        /// <param name="crypto"></param>
        /// <param name="link">Payment-link slug for attribution. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<CryptoGate.Client.ApiResponse<Object>> HostedCheckoutRedirectWithHttpInfoAsync(string pk, string amount, CryptoSymbol crypto, string? link = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'pk' is set
            if (pk == null)
                throw new CryptoGate.Client.ApiException(400, "Missing required parameter 'pk' when calling SystemApi->HostedCheckoutRedirect");

            // verify the required parameter 'amount' is set
            if (amount == null)
                throw new CryptoGate.Client.ApiException(400, "Missing required parameter 'amount' when calling SystemApi->HostedCheckoutRedirect");


            CryptoGate.Client.RequestOptions localVarRequestOptions = new CryptoGate.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = CryptoGate.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = CryptoGate.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "pk", pk));
            localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "amount", amount));
            localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "crypto", crypto));
            if (link != null)
            {
                localVarRequestOptions.QueryParameters.Add(CryptoGate.Client.ClientUtils.ParameterToMultiMap("", "link", link));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/pay", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HostedCheckoutRedirect", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
