/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using GriffNode.SDK.Client;
using GriffNode.SDK.Api;
// uncomment below to import models
//using GriffNode.SDK.Model;

namespace GriffNode.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing AccountApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AccountApiTests : IDisposable
    {
        private AccountApi instance;

        public AccountApiTests()
        {
            instance = new AccountApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AccountApi
            //Assert.IsType<AccountApi>(instance);
        }

        /// <summary>
        /// Test GetAccount
        /// </summary>
        [Fact]
        public void GetAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAccount();
            //Assert.IsType<GetAccount200Response>(response);
        }

        /// <summary>
        /// Test GetStats
        /// </summary>
        [Fact]
        public void GetStatsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetStats();
            //Assert.IsType<GetStats200Response>(response);
        }

        /// <summary>
        /// Test ListBalances
        /// </summary>
        [Fact]
        public void ListBalancesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListBalances();
            //Assert.IsType<ListBalances200Response>(response);
        }

        /// <summary>
        /// Test ListInvoices
        /// </summary>
        [Fact]
        public void ListInvoicesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //var response = instance.ListInvoices(limit, offset);
            //Assert.IsType<ListInvoices200Response>(response);
        }

        /// <summary>
        /// Test ListPlans
        /// </summary>
        [Fact]
        public void ListPlansTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListPlans();
            //Assert.IsType<ListPlans200Response>(response);
        }
    }
}
