/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using GriffNode.SDK.Client;
using GriffNode.SDK.Api;
// uncomment below to import models
//using GriffNode.SDK.Model;

namespace GriffNode.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing MarketDataApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MarketDataApiTests : IDisposable
    {
        private MarketDataApi instance;

        public MarketDataApiTests()
        {
            instance = new MarketDataApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarketDataApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MarketDataApi
            //Assert.IsType<MarketDataApi>(instance);
        }

        /// <summary>
        /// Test GetPrices
        /// </summary>
        [Fact]
        public void GetPricesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetPrices();
            //Assert.IsType<GetPrices200Response>(response);
        }

        /// <summary>
        /// Test ListCryptocurrencies
        /// </summary>
        [Fact]
        public void ListCryptocurrenciesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListCryptocurrencies();
            //Assert.IsType<ListCryptocurrencies200Response>(response);
        }

        /// <summary>
        /// Test ListMerchantCryptocurrencies
        /// </summary>
        [Fact]
        public void ListMerchantCryptocurrenciesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListMerchantCryptocurrencies();
            //Assert.IsType<ListCryptocurrencies200Response>(response);
        }
    }
}
