/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GriffNode.SDK.Client.FileParameter;
using OpenAPIDateConverter = GriffNode.SDK.Client.OpenAPIDateConverter;

namespace GriffNode.SDK.Model
{
    /// <summary>
    /// AccountLimits
    /// </summary>
    [DataContract(Name = "Account_limits")]
    public partial class AccountLimits : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountLimits" /> class.
        /// </summary>
        /// <param name="apiRateLimitPerMinute">apiRateLimitPerMinute.</param>
        /// <param name="apiRateLimitPerHour">apiRateLimitPerHour.</param>
        /// <param name="webhookSupport">webhookSupport.</param>
        public AccountLimits(int apiRateLimitPerMinute = default(int), int apiRateLimitPerHour = default(int), bool webhookSupport = default(bool))
        {
            this.ApiRateLimitPerMinute = apiRateLimitPerMinute;
            this.ApiRateLimitPerHour = apiRateLimitPerHour;
            this.WebhookSupport = webhookSupport;
        }

        /// <summary>
        /// Gets or Sets ApiRateLimitPerMinute
        /// </summary>
        [DataMember(Name = "api_rate_limit_per_minute", EmitDefaultValue = false)]
        public int ApiRateLimitPerMinute { get; set; }

        /// <summary>
        /// Gets or Sets ApiRateLimitPerHour
        /// </summary>
        [DataMember(Name = "api_rate_limit_per_hour", EmitDefaultValue = false)]
        public int ApiRateLimitPerHour { get; set; }

        /// <summary>
        /// Gets or Sets WebhookSupport
        /// </summary>
        [DataMember(Name = "webhook_support", EmitDefaultValue = true)]
        public bool WebhookSupport { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountLimits {\n");
            sb.Append("  ApiRateLimitPerMinute: ").Append(ApiRateLimitPerMinute).Append("\n");
            sb.Append("  ApiRateLimitPerHour: ").Append(ApiRateLimitPerHour).Append("\n");
            sb.Append("  WebhookSupport: ").Append(WebhookSupport).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
