/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GriffNode.SDK.Client.FileParameter;
using OpenAPIDateConverter = GriffNode.SDK.Client.OpenAPIDateConverter;

namespace GriffNode.SDK.Model
{
    /// <summary>
    /// AccountPlan
    /// </summary>
    [DataContract(Name = "Account_plan")]
    public partial class AccountPlan : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Tier
        /// </summary>
        [DataMember(Name = "tier", EmitDefaultValue = false)]
        public PlanTier? Tier { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountPlan" /> class.
        /// </summary>
        /// <param name="tier">tier.</param>
        /// <param name="billingCycle">billingCycle.</param>
        /// <param name="autoRenewal">autoRenewal.</param>
        /// <param name="expiresAt">expiresAt.</param>
        public AccountPlan(PlanTier? tier = default(PlanTier?), string billingCycle = default(string), bool autoRenewal = default(bool), DateTime? expiresAt = default(DateTime?))
        {
            this.Tier = tier;
            this.BillingCycle = billingCycle;
            this.AutoRenewal = autoRenewal;
            this.ExpiresAt = expiresAt;
        }

        /// <summary>
        /// Gets or Sets BillingCycle
        /// </summary>
        [DataMember(Name = "billing_cycle", EmitDefaultValue = false)]
        public string BillingCycle { get; set; }

        /// <summary>
        /// Gets or Sets AutoRenewal
        /// </summary>
        [DataMember(Name = "auto_renewal", EmitDefaultValue = true)]
        public bool AutoRenewal { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name = "expires_at", EmitDefaultValue = true)]
        public DateTime? ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountPlan {\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  BillingCycle: ").Append(BillingCycle).Append("\n");
            sb.Append("  AutoRenewal: ").Append(AutoRenewal).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
