/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GriffNode.SDK.Client.FileParameter;
using OpenAPIDateConverter = GriffNode.SDK.Client.OpenAPIDateConverter;

namespace GriffNode.SDK.Model
{
    /// <summary>
    /// CreateTransactionRequest
    /// </summary>
    [DataContract(Name = "CreateTransactionRequest")]
    public partial class CreateTransactionRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Crypto
        /// </summary>
        [DataMember(Name = "crypto", IsRequired = true, EmitDefaultValue = true)]
        public CryptoSymbol Crypto { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyFiat
        /// </summary>
        [DataMember(Name = "currency_fiat", EmitDefaultValue = false)]
        public FiatCurrency? CurrencyFiat { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTransactionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateTransactionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTransactionRequest" /> class.
        /// </summary>
        /// <param name="crypto">crypto (required).</param>
        /// <param name="amount">Fiat amount (≥ 1.00 USD equivalent). (required).</param>
        /// <param name="currencyFiat">currencyFiat.</param>
        /// <param name="metadata">Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total)..</param>
        /// <param name="customerEmail">customerEmail.</param>
        /// <param name="successUrl">successUrl.</param>
        /// <param name="cancelUrl">cancelUrl.</param>
        public CreateTransactionRequest(CryptoSymbol crypto = default(CryptoSymbol), decimal amount = default(decimal), FiatCurrency? currencyFiat = default(FiatCurrency?), Dictionary<string, string> metadata = default(Dictionary<string, string>), string customerEmail = default(string), string successUrl = default(string), string cancelUrl = default(string))
        {
            this.Crypto = crypto;
            this.Amount = amount;
            this.CurrencyFiat = currencyFiat;
            this.Metadata = metadata;
            this.CustomerEmail = customerEmail;
            this.SuccessUrl = successUrl;
            this.CancelUrl = cancelUrl;
        }

        /// <summary>
        /// Fiat amount (≥ 1.00 USD equivalent).
        /// </summary>
        /// <value>Fiat amount (≥ 1.00 USD equivalent).</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
        /// </summary>
        /// <value>Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Gets or Sets CustomerEmail
        /// </summary>
        [DataMember(Name = "customer_email", EmitDefaultValue = true)]
        public string CustomerEmail { get; set; }

        /// <summary>
        /// Gets or Sets SuccessUrl
        /// </summary>
        [DataMember(Name = "success_url", EmitDefaultValue = true)]
        public string SuccessUrl { get; set; }

        /// <summary>
        /// Gets or Sets CancelUrl
        /// </summary>
        [DataMember(Name = "cancel_url", EmitDefaultValue = true)]
        public string CancelUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTransactionRequest {\n");
            sb.Append("  Crypto: ").Append(Crypto).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  CurrencyFiat: ").Append(CurrencyFiat).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  CustomerEmail: ").Append(CustomerEmail).Append("\n");
            sb.Append("  SuccessUrl: ").Append(SuccessUrl).Append("\n");
            sb.Append("  CancelUrl: ").Append(CancelUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
