/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GriffNode.SDK.Client.FileParameter;
using OpenAPIDateConverter = GriffNode.SDK.Client.OpenAPIDateConverter;

namespace GriffNode.SDK.Model
{
    /// <summary>
    /// GetStats200ResponseData
    /// </summary>
    [DataContract(Name = "getStats_200_response_data")]
    public partial class GetStats200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStats200ResponseData" /> class.
        /// </summary>
        /// <param name="totalTransactions">totalTransactions.</param>
        /// <param name="monthlyTransactions">monthlyTransactions.</param>
        /// <param name="totalVolumeFiat">totalVolumeFiat.</param>
        /// <param name="uniqueCustomers">uniqueCustomers.</param>
        public GetStats200ResponseData(int totalTransactions = default(int), int monthlyTransactions = default(int), decimal totalVolumeFiat = default(decimal), int uniqueCustomers = default(int))
        {
            this.TotalTransactions = totalTransactions;
            this.MonthlyTransactions = monthlyTransactions;
            this.TotalVolumeFiat = totalVolumeFiat;
            this.UniqueCustomers = uniqueCustomers;
        }

        /// <summary>
        /// Gets or Sets TotalTransactions
        /// </summary>
        [DataMember(Name = "total_transactions", EmitDefaultValue = false)]
        public int TotalTransactions { get; set; }

        /// <summary>
        /// Gets or Sets MonthlyTransactions
        /// </summary>
        [DataMember(Name = "monthly_transactions", EmitDefaultValue = false)]
        public int MonthlyTransactions { get; set; }

        /// <summary>
        /// Gets or Sets TotalVolumeFiat
        /// </summary>
        [DataMember(Name = "total_volume_fiat", EmitDefaultValue = false)]
        public decimal TotalVolumeFiat { get; set; }

        /// <summary>
        /// Gets or Sets UniqueCustomers
        /// </summary>
        [DataMember(Name = "unique_customers", EmitDefaultValue = false)]
        public int UniqueCustomers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetStats200ResponseData {\n");
            sb.Append("  TotalTransactions: ").Append(TotalTransactions).Append("\n");
            sb.Append("  MonthlyTransactions: ").Append(MonthlyTransactions).Append("\n");
            sb.Append("  TotalVolumeFiat: ").Append(TotalVolumeFiat).Append("\n");
            sb.Append("  UniqueCustomers: ").Append(UniqueCustomers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
