/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GriffNode.SDK.Client.FileParameter;
using OpenAPIDateConverter = GriffNode.SDK.Client.OpenAPIDateConverter;

namespace GriffNode.SDK.Model
{
    /// <summary>
    /// Invoice
    /// </summary>
    [DataContract(Name = "Invoice")]
    public partial class Invoice : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets CurrencyFiat
        /// </summary>
        [DataMember(Name = "currency_fiat", EmitDefaultValue = false)]
        public FiatCurrency? CurrencyFiat { get; set; }

        /// <summary>
        /// Gets or Sets CryptoSymbol
        /// </summary>
        [DataMember(Name = "crypto_symbol", EmitDefaultValue = false)]
        public CryptoSymbol? CryptoSymbol { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Invoice" /> class.
        /// </summary>
        /// <param name="transactionId">transactionId.</param>
        /// <param name="purchaseType">purchaseType.</param>
        /// <param name="amountFiat">amountFiat.</param>
        /// <param name="currencyFiat">currencyFiat.</param>
        /// <param name="status">status.</param>
        /// <param name="cryptoSymbol">cryptoSymbol.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="confirmedAt">confirmedAt.</param>
        /// <param name="expiresAt">expiresAt.</param>
        public Invoice(string transactionId = default(string), string purchaseType = default(string), decimal amountFiat = default(decimal), FiatCurrency? currencyFiat = default(FiatCurrency?), string status = default(string), CryptoSymbol? cryptoSymbol = default(CryptoSymbol?), DateTime createdAt = default(DateTime), DateTime? confirmedAt = default(DateTime?), DateTime expiresAt = default(DateTime))
        {
            this.TransactionId = transactionId;
            this.PurchaseType = purchaseType;
            this.AmountFiat = amountFiat;
            this.CurrencyFiat = currencyFiat;
            this.Status = status;
            this.CryptoSymbol = cryptoSymbol;
            this.CreatedAt = createdAt;
            this.ConfirmedAt = confirmedAt;
            this.ExpiresAt = expiresAt;
        }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transaction_id", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseType
        /// </summary>
        [DataMember(Name = "purchase_type", EmitDefaultValue = false)]
        public string PurchaseType { get; set; }

        /// <summary>
        /// Gets or Sets AmountFiat
        /// </summary>
        [DataMember(Name = "amount_fiat", EmitDefaultValue = false)]
        public decimal AmountFiat { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ConfirmedAt
        /// </summary>
        [DataMember(Name = "confirmed_at", EmitDefaultValue = true)]
        public DateTime? ConfirmedAt { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name = "expires_at", EmitDefaultValue = false)]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Invoice {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  PurchaseType: ").Append(PurchaseType).Append("\n");
            sb.Append("  AmountFiat: ").Append(AmountFiat).Append("\n");
            sb.Append("  CurrencyFiat: ").Append(CurrencyFiat).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CryptoSymbol: ").Append(CryptoSymbol).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ConfirmedAt: ").Append(ConfirmedAt).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
