/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = GriffNode.SDK.Client.FileParameter;
using OpenAPIDateConverter = GriffNode.SDK.Client.OpenAPIDateConverter;

namespace GriffNode.SDK.Model
{
    /// <summary>
    /// Plan
    /// </summary>
    [DataContract(Name = "Plan")]
    public partial class Plan : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Tier
        /// </summary>
        [DataMember(Name = "tier", EmitDefaultValue = false)]
        public PlanTier? Tier { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Plan" /> class.
        /// </summary>
        /// <param name="tier">tier.</param>
        /// <param name="monthlyPriceUsd">monthlyPriceUsd.</param>
        /// <param name="yearlyPriceUsd">yearlyPriceUsd.</param>
        /// <param name="monthlyTransactionLimit">monthlyTransactionLimit.</param>
        /// <param name="overageCostPerTx">overageCostPerTx.</param>
        /// <param name="webhookSupport">webhookSupport.</param>
        /// <param name="webhookLimit">webhookLimit.</param>
        /// <param name="ipWhitelist">ipWhitelist.</param>
        /// <param name="apiRateLimitPerMinute">apiRateLimitPerMinute.</param>
        /// <param name="apiRateLimitPerHour">apiRateLimitPerHour.</param>
        /// <param name="customPricing">customPricing.</param>
        public Plan(PlanTier? tier = default(PlanTier?), decimal? monthlyPriceUsd = default(decimal?), decimal? yearlyPriceUsd = default(decimal?), int? monthlyTransactionLimit = default(int?), decimal overageCostPerTx = default(decimal), bool webhookSupport = default(bool), int? webhookLimit = default(int?), bool ipWhitelist = default(bool), int apiRateLimitPerMinute = default(int), int apiRateLimitPerHour = default(int), bool customPricing = default(bool))
        {
            this.Tier = tier;
            this.MonthlyPriceUsd = monthlyPriceUsd;
            this.YearlyPriceUsd = yearlyPriceUsd;
            this.MonthlyTransactionLimit = monthlyTransactionLimit;
            this.OverageCostPerTx = overageCostPerTx;
            this.WebhookSupport = webhookSupport;
            this.WebhookLimit = webhookLimit;
            this.IpWhitelist = ipWhitelist;
            this.ApiRateLimitPerMinute = apiRateLimitPerMinute;
            this.ApiRateLimitPerHour = apiRateLimitPerHour;
            this.CustomPricing = customPricing;
        }

        /// <summary>
        /// Gets or Sets MonthlyPriceUsd
        /// </summary>
        [DataMember(Name = "monthly_price_usd", EmitDefaultValue = true)]
        public decimal? MonthlyPriceUsd { get; set; }

        /// <summary>
        /// Gets or Sets YearlyPriceUsd
        /// </summary>
        [DataMember(Name = "yearly_price_usd", EmitDefaultValue = true)]
        public decimal? YearlyPriceUsd { get; set; }

        /// <summary>
        /// Gets or Sets MonthlyTransactionLimit
        /// </summary>
        [DataMember(Name = "monthly_transaction_limit", EmitDefaultValue = true)]
        public int? MonthlyTransactionLimit { get; set; }

        /// <summary>
        /// Gets or Sets OverageCostPerTx
        /// </summary>
        [DataMember(Name = "overage_cost_per_tx", EmitDefaultValue = false)]
        public decimal OverageCostPerTx { get; set; }

        /// <summary>
        /// Gets or Sets WebhookSupport
        /// </summary>
        [DataMember(Name = "webhook_support", EmitDefaultValue = true)]
        public bool WebhookSupport { get; set; }

        /// <summary>
        /// Gets or Sets WebhookLimit
        /// </summary>
        [DataMember(Name = "webhook_limit", EmitDefaultValue = true)]
        public int? WebhookLimit { get; set; }

        /// <summary>
        /// Gets or Sets IpWhitelist
        /// </summary>
        [DataMember(Name = "ip_whitelist", EmitDefaultValue = true)]
        public bool IpWhitelist { get; set; }

        /// <summary>
        /// Gets or Sets ApiRateLimitPerMinute
        /// </summary>
        [DataMember(Name = "api_rate_limit_per_minute", EmitDefaultValue = false)]
        public int ApiRateLimitPerMinute { get; set; }

        /// <summary>
        /// Gets or Sets ApiRateLimitPerHour
        /// </summary>
        [DataMember(Name = "api_rate_limit_per_hour", EmitDefaultValue = false)]
        public int ApiRateLimitPerHour { get; set; }

        /// <summary>
        /// Gets or Sets CustomPricing
        /// </summary>
        [DataMember(Name = "custom_pricing", EmitDefaultValue = true)]
        public bool CustomPricing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Plan {\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  MonthlyPriceUsd: ").Append(MonthlyPriceUsd).Append("\n");
            sb.Append("  YearlyPriceUsd: ").Append(YearlyPriceUsd).Append("\n");
            sb.Append("  MonthlyTransactionLimit: ").Append(MonthlyTransactionLimit).Append("\n");
            sb.Append("  OverageCostPerTx: ").Append(OverageCostPerTx).Append("\n");
            sb.Append("  WebhookSupport: ").Append(WebhookSupport).Append("\n");
            sb.Append("  WebhookLimit: ").Append(WebhookLimit).Append("\n");
            sb.Append("  IpWhitelist: ").Append(IpWhitelist).Append("\n");
            sb.Append("  ApiRateLimitPerMinute: ").Append(ApiRateLimitPerMinute).Append("\n");
            sb.Append("  ApiRateLimitPerHour: ").Append(ApiRateLimitPerHour).Append("\n");
            sb.Append("  CustomPricing: ").Append(CustomPricing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
