/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using GriffNode.SDK.Client;
using GriffNode.SDK.Model;

namespace GriffNode.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMarketDataApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated)
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetPrices200Response</returns>
        GetPrices200Response GetPrices();

        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetPrices200Response</returns>
        ApiResponse<GetPrices200Response> GetPricesWithHttpInfo();
        /// <summary>
        /// All supported cryptocurrencies and tokens
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCryptocurrencies200Response</returns>
        ListCryptocurrencies200Response ListCryptocurrencies();

        /// <summary>
        /// All supported cryptocurrencies and tokens
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCryptocurrencies200Response</returns>
        ApiResponse<ListCryptocurrencies200Response> ListCryptocurrenciesWithHttpInfo();
        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCryptocurrencies200Response</returns>
        ListCryptocurrencies200Response ListMerchantCryptocurrencies();

        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCryptocurrencies200Response</returns>
        ApiResponse<ListCryptocurrencies200Response> ListMerchantCryptocurrenciesWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMarketDataApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPrices200Response</returns>
        System.Threading.Tasks.Task<GetPrices200Response> GetPricesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPrices200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetPrices200Response>> GetPricesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// All supported cryptocurrencies and tokens
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListCryptocurrencies200Response</returns>
        System.Threading.Tasks.Task<ListCryptocurrencies200Response> ListCryptocurrenciesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// All supported cryptocurrencies and tokens
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListCryptocurrencies200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListCryptocurrencies200Response>> ListCryptocurrenciesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListCryptocurrencies200Response</returns>
        System.Threading.Tasks.Task<ListCryptocurrencies200Response> ListMerchantCryptocurrenciesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListCryptocurrencies200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListCryptocurrencies200Response>> ListMerchantCryptocurrenciesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMarketDataApi : IMarketDataApiSync, IMarketDataApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MarketDataApi : IDisposable, IMarketDataApi
    {
        private GriffNode.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MarketDataApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MarketDataApi(string basePath)
        {
            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                new GriffNode.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MarketDataApi(GriffNode.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MarketDataApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MarketDataApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                new GriffNode.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MarketDataApi(HttpClient client, GriffNode.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MarketDataApi(GriffNode.SDK.Client.ISynchronousClient client, GriffNode.SDK.Client.IAsynchronousClient asyncClient, GriffNode.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public GriffNode.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GriffNode.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GriffNode.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GriffNode.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GriffNode.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetPrices200Response</returns>
        public GetPrices200Response GetPrices()
        {
            GriffNode.SDK.Client.ApiResponse<GetPrices200Response> localVarResponse = GetPricesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetPrices200Response</returns>
        public GriffNode.SDK.Client.ApiResponse<GetPrices200Response> GetPricesWithHttpInfo()
        {
            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetPrices200Response>("/prices", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPrices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPrices200Response</returns>
        public async System.Threading.Tasks.Task<GetPrices200Response> GetPricesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GriffNode.SDK.Client.ApiResponse<GetPrices200Response> localVarResponse = await GetPricesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Current crypto and fiat exchange rates (USD-denominated) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPrices200Response)</returns>
        public async System.Threading.Tasks.Task<GriffNode.SDK.Client.ApiResponse<GetPrices200Response>> GetPricesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetPrices200Response>("/prices", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPrices", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// All supported cryptocurrencies and tokens 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCryptocurrencies200Response</returns>
        public ListCryptocurrencies200Response ListCryptocurrencies()
        {
            GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response> localVarResponse = ListCryptocurrenciesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// All supported cryptocurrencies and tokens 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCryptocurrencies200Response</returns>
        public GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response> ListCryptocurrenciesWithHttpInfo()
        {
            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListCryptocurrencies200Response>("/cryptos/list", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCryptocurrencies", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// All supported cryptocurrencies and tokens 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListCryptocurrencies200Response</returns>
        public async System.Threading.Tasks.Task<ListCryptocurrencies200Response> ListCryptocurrenciesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response> localVarResponse = await ListCryptocurrenciesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// All supported cryptocurrencies and tokens 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListCryptocurrencies200Response)</returns>
        public async System.Threading.Tasks.Task<GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response>> ListCryptocurrenciesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListCryptocurrencies200Response>("/cryptos/list", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListCryptocurrencies", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCryptocurrencies200Response</returns>
        public ListCryptocurrencies200Response ListMerchantCryptocurrencies()
        {
            GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response> localVarResponse = ListMerchantCryptocurrenciesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCryptocurrencies200Response</returns>
        public GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response> ListMerchantCryptocurrenciesWithHttpInfo()
        {
            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListCryptocurrencies200Response>("/merchant/cryptos", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMerchantCryptocurrencies", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListCryptocurrencies200Response</returns>
        public async System.Threading.Tasks.Task<ListCryptocurrencies200Response> ListMerchantCryptocurrenciesAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response> localVarResponse = await ListMerchantCryptocurrenciesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cryptocurrencies this merchant has wallets configured for 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListCryptocurrencies200Response)</returns>
        public async System.Threading.Tasks.Task<GriffNode.SDK.Client.ApiResponse<ListCryptocurrencies200Response>> ListMerchantCryptocurrenciesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListCryptocurrencies200Response>("/merchant/cryptos", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListMerchantCryptocurrencies", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
