/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using GriffNode.SDK.Client;
using GriffNode.SDK.Model;

namespace GriffNode.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITransactionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans)
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>TransactionEnvelope</returns>
        TransactionEnvelope CreateDetailedTransaction(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?));

        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>ApiResponse of TransactionEnvelope</returns>
        ApiResponse<TransactionEnvelope> CreateDetailedTransactionWithHttpInfo(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?));
        /// <summary>
        /// Create a payment transaction
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>TransactionEnvelope</returns>
        TransactionEnvelope CreateTransaction(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?));

        /// <summary>
        /// Create a payment transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>ApiResponse of TransactionEnvelope</returns>
        ApiResponse<TransactionEnvelope> CreateTransactionWithHttpInfo(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?));
        /// <summary>
        /// Retrieve a single transaction
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <returns>TransactionEnvelope</returns>
        TransactionEnvelope GetTransaction(string transactionId);

        /// <summary>
        /// Retrieve a single transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <returns>ApiResponse of TransactionEnvelope</returns>
        ApiResponse<TransactionEnvelope> GetTransactionWithHttpInfo(string transactionId);
        /// <summary>
        /// List the merchant&#39;s transactions (newest first)
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <returns>ListTransactions200Response</returns>
        ListTransactions200Response ListTransactions(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?));

        /// <summary>
        /// List the merchant&#39;s transactions (newest first)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <returns>ApiResponse of ListTransactions200Response</returns>
        ApiResponse<ListTransactions200Response> ListTransactionsWithHttpInfo(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITransactionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionEnvelope</returns>
        System.Threading.Tasks.Task<TransactionEnvelope> CreateDetailedTransactionAsync(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionEnvelope>> CreateDetailedTransactionWithHttpInfoAsync(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Create a payment transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionEnvelope</returns>
        System.Threading.Tasks.Task<TransactionEnvelope> CreateTransactionAsync(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create a payment transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionEnvelope>> CreateTransactionWithHttpInfoAsync(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Retrieve a single transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionEnvelope</returns>
        System.Threading.Tasks.Task<TransactionEnvelope> GetTransactionAsync(string transactionId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Retrieve a single transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionEnvelope>> GetTransactionWithHttpInfoAsync(string transactionId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// List the merchant&#39;s transactions (newest first)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListTransactions200Response</returns>
        System.Threading.Tasks.Task<ListTransactions200Response> ListTransactionsAsync(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// List the merchant&#39;s transactions (newest first)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListTransactions200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListTransactions200Response>> ListTransactionsWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITransactionsApi : ITransactionsApiSync, ITransactionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TransactionsApi : IDisposable, ITransactionsApi
    {
        private GriffNode.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public TransactionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public TransactionsApi(string basePath)
        {
            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                new GriffNode.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public TransactionsApi(GriffNode.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TransactionsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TransactionsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                new GriffNode.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TransactionsApi(HttpClient client, GriffNode.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = GriffNode.SDK.Client.Configuration.MergeConfigurations(
                GriffNode.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new GriffNode.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public TransactionsApi(GriffNode.SDK.Client.ISynchronousClient client, GriffNode.SDK.Client.IAsynchronousClient asyncClient, GriffNode.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GriffNode.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public GriffNode.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GriffNode.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GriffNode.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GriffNode.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GriffNode.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>TransactionEnvelope</returns>
        public TransactionEnvelope CreateDetailedTransaction(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?))
        {
            GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> localVarResponse = CreateDetailedTransactionWithHttpInfo(createDetailedTransactionRequest, xIdempotencyKey);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>ApiResponse of TransactionEnvelope</returns>
        public GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> CreateDetailedTransactionWithHttpInfo(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?))
        {
            // verify the required parameter 'createDetailedTransactionRequest' is set
            if (createDetailedTransactionRequest == null)
                throw new GriffNode.SDK.Client.ApiException(400, "Missing required parameter 'createDetailedTransactionRequest' when calling TransactionsApi->CreateDetailedTransaction");

            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xIdempotencyKey != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Idempotency-Key", GriffNode.SDK.Client.ClientUtils.ParameterToString(xIdempotencyKey)); // header parameter
            }
            localVarRequestOptions.Data = createDetailedTransactionRequest;

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TransactionEnvelope>("/transactions/create-detailed", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDetailedTransaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionEnvelope</returns>
        public async System.Threading.Tasks.Task<TransactionEnvelope> CreateDetailedTransactionAsync(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> localVarResponse = await CreateDetailedTransactionWithHttpInfoAsync(createDetailedTransactionRequest, xIdempotencyKey, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an itemized transaction (Professional/Enterprise plans) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createDetailedTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionEnvelope)</returns>
        public async System.Threading.Tasks.Task<GriffNode.SDK.Client.ApiResponse<TransactionEnvelope>> CreateDetailedTransactionWithHttpInfoAsync(CreateDetailedTransactionRequest createDetailedTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'createDetailedTransactionRequest' is set
            if (createDetailedTransactionRequest == null)
                throw new GriffNode.SDK.Client.ApiException(400, "Missing required parameter 'createDetailedTransactionRequest' when calling TransactionsApi->CreateDetailedTransaction");


            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xIdempotencyKey != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Idempotency-Key", GriffNode.SDK.Client.ClientUtils.ParameterToString(xIdempotencyKey)); // header parameter
            }
            localVarRequestOptions.Data = createDetailedTransactionRequest;

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<TransactionEnvelope>("/transactions/create-detailed", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDetailedTransaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a payment transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>TransactionEnvelope</returns>
        public TransactionEnvelope CreateTransaction(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?))
        {
            GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> localVarResponse = CreateTransactionWithHttpInfo(createTransactionRequest, xIdempotencyKey);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a payment transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <returns>ApiResponse of TransactionEnvelope</returns>
        public GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> CreateTransactionWithHttpInfo(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?))
        {
            // verify the required parameter 'createTransactionRequest' is set
            if (createTransactionRequest == null)
                throw new GriffNode.SDK.Client.ApiException(400, "Missing required parameter 'createTransactionRequest' when calling TransactionsApi->CreateTransaction");

            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xIdempotencyKey != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Idempotency-Key", GriffNode.SDK.Client.ClientUtils.ParameterToString(xIdempotencyKey)); // header parameter
            }
            localVarRequestOptions.Data = createTransactionRequest;

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TransactionEnvelope>("/transactions/create", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTransaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a payment transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionEnvelope</returns>
        public async System.Threading.Tasks.Task<TransactionEnvelope> CreateTransactionAsync(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> localVarResponse = await CreateTransactionWithHttpInfoAsync(createTransactionRequest, xIdempotencyKey, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a payment transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTransactionRequest"></param>
        /// <param name="xIdempotencyKey">Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can&#39;t double-charge the customer.  (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionEnvelope)</returns>
        public async System.Threading.Tasks.Task<GriffNode.SDK.Client.ApiResponse<TransactionEnvelope>> CreateTransactionWithHttpInfoAsync(CreateTransactionRequest createTransactionRequest, string? xIdempotencyKey = default(string?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'createTransactionRequest' is set
            if (createTransactionRequest == null)
                throw new GriffNode.SDK.Client.ApiException(400, "Missing required parameter 'createTransactionRequest' when calling TransactionsApi->CreateTransaction");


            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xIdempotencyKey != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-Idempotency-Key", GriffNode.SDK.Client.ClientUtils.ParameterToString(xIdempotencyKey)); // header parameter
            }
            localVarRequestOptions.Data = createTransactionRequest;

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<TransactionEnvelope>("/transactions/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTransaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve a single transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <returns>TransactionEnvelope</returns>
        public TransactionEnvelope GetTransaction(string transactionId)
        {
            GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> localVarResponse = GetTransactionWithHttpInfo(transactionId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve a single transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <returns>ApiResponse of TransactionEnvelope</returns>
        public GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> GetTransactionWithHttpInfo(string transactionId)
        {
            // verify the required parameter 'transactionId' is set
            if (transactionId == null)
                throw new GriffNode.SDK.Client.ApiException(400, "Missing required parameter 'transactionId' when calling TransactionsApi->GetTransaction");

            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("transaction_id", GriffNode.SDK.Client.ClientUtils.ParameterToString(transactionId)); // path parameter

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TransactionEnvelope>("/transactions/{transaction_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTransaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve a single transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionEnvelope</returns>
        public async System.Threading.Tasks.Task<TransactionEnvelope> GetTransactionAsync(string transactionId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GriffNode.SDK.Client.ApiResponse<TransactionEnvelope> localVarResponse = await GetTransactionWithHttpInfoAsync(transactionId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve a single transaction 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionEnvelope)</returns>
        public async System.Threading.Tasks.Task<GriffNode.SDK.Client.ApiResponse<TransactionEnvelope>> GetTransactionWithHttpInfoAsync(string transactionId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'transactionId' is set
            if (transactionId == null)
                throw new GriffNode.SDK.Client.ApiException(400, "Missing required parameter 'transactionId' when calling TransactionsApi->GetTransaction");


            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("transaction_id", GriffNode.SDK.Client.ClientUtils.ParameterToString(transactionId)); // path parameter

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TransactionEnvelope>("/transactions/{transaction_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTransaction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the merchant&#39;s transactions (newest first) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <returns>ListTransactions200Response</returns>
        public ListTransactions200Response ListTransactions(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?))
        {
            GriffNode.SDK.Client.ApiResponse<ListTransactions200Response> localVarResponse = ListTransactionsWithHttpInfo(limit, offset, status, crypto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the merchant&#39;s transactions (newest first) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <returns>ApiResponse of ListTransactions200Response</returns>
        public GriffNode.SDK.Client.ApiResponse<ListTransactions200Response> ListTransactionsWithHttpInfo(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?))
        {
            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (crypto != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "crypto", crypto));
            }

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListTransactions200Response>("/transactions/list", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTransactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List the merchant&#39;s transactions (newest first) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListTransactions200Response</returns>
        public async System.Threading.Tasks.Task<ListTransactions200Response> ListTransactionsAsync(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            GriffNode.SDK.Client.ApiResponse<ListTransactions200Response> localVarResponse = await ListTransactionsWithHttpInfoAsync(limit, offset, status, crypto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List the merchant&#39;s transactions (newest first) 
        /// </summary>
        /// <exception cref="GriffNode.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 20)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="crypto"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListTransactions200Response)</returns>
        public async System.Threading.Tasks.Task<GriffNode.SDK.Client.ApiResponse<ListTransactions200Response>> ListTransactionsWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), TransactionStatus? status = default(TransactionStatus?), CryptoSymbol? crypto = default(CryptoSymbol?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            GriffNode.SDK.Client.RequestOptions localVarRequestOptions = new GriffNode.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = GriffNode.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = GriffNode.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (crypto != null)
            {
                localVarRequestOptions.QueryParameters.Add(GriffNode.SDK.Client.ClientUtils.ParameterToMultiMap("", "crypto", crypto));
            }

            // authentication (SecretKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListTransactions200Response>("/transactions/list", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTransactions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
