/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CryptoGate.Client.FileParameter;
using OpenAPIDateConverter = CryptoGate.Client.OpenAPIDateConverter;

namespace CryptoGate.Model
{
    /// <summary>
    /// CreateBillingCheckoutRequest
    /// </summary>
    [DataContract(Name = "createBillingCheckout_request")]
    public partial class CreateBillingCheckoutRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Tier
        /// </summary>
        [DataMember(Name = "tier", IsRequired = true, EmitDefaultValue = true)]
        public PlanTier Tier { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBillingCheckoutRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateBillingCheckoutRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBillingCheckoutRequest" /> class.
        /// </summary>
        /// <param name="tier">tier (required).</param>
        /// <param name="billingMonths">billingMonths (default to 1).</param>
        /// <param name="paymentMethod">paymentMethod (default to &quot;crypto&quot;).</param>
        public CreateBillingCheckoutRequest(PlanTier tier = default(PlanTier), int billingMonths = 1, string paymentMethod = @"crypto")
        {
            this.Tier = tier;
            this.BillingMonths = billingMonths;
            // use default value if no "paymentMethod" provided
            this.PaymentMethod = paymentMethod ?? @"crypto";
        }

        /// <summary>
        /// Gets or Sets BillingMonths
        /// </summary>
        [DataMember(Name = "billing_months", EmitDefaultValue = false)]
        public int BillingMonths { get; set; }

        /// <summary>
        /// Gets or Sets PaymentMethod
        /// </summary>
        [DataMember(Name = "payment_method", EmitDefaultValue = false)]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateBillingCheckoutRequest {\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  BillingMonths: ").Append(BillingMonths).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // BillingMonths (int) minimum
            if (this.BillingMonths < (int)1)
            {
                yield return new ValidationResult("Invalid value for BillingMonths, must be a value greater than or equal to 1.", new [] { "BillingMonths" });
            }

            yield break;
        }
    }

}
