/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CryptoGate.Client.FileParameter;
using OpenAPIDateConverter = CryptoGate.Client.OpenAPIDateConverter;

namespace CryptoGate.Model
{
    /// <summary>
    /// Supported coin/token symbol. /cryptos/list is authoritative at runtime.
    /// </summary>
    /// <value>Supported coin/token symbol. /cryptos/list is authoritative at runtime.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CryptoSymbol
    {
        /// <summary>
        /// Enum BTC for value: BTC
        /// </summary>
        [EnumMember(Value = "BTC")]
        BTC = 1,

        /// <summary>
        /// Enum LTC for value: LTC
        /// </summary>
        [EnumMember(Value = "LTC")]
        LTC = 2,

        /// <summary>
        /// Enum DOGE for value: DOGE
        /// </summary>
        [EnumMember(Value = "DOGE")]
        DOGE = 3,

        /// <summary>
        /// Enum DASH for value: DASH
        /// </summary>
        [EnumMember(Value = "DASH")]
        DASH = 4,

        /// <summary>
        /// Enum ETH for value: ETH
        /// </summary>
        [EnumMember(Value = "ETH")]
        ETH = 5,

        /// <summary>
        /// Enum USDT for value: USDT
        /// </summary>
        [EnumMember(Value = "USDT")]
        USDT = 6,

        /// <summary>
        /// Enum USDC for value: USDC
        /// </summary>
        [EnumMember(Value = "USDC")]
        USDC = 7,

        /// <summary>
        /// Enum DAI for value: DAI
        /// </summary>
        [EnumMember(Value = "DAI")]
        DAI = 8,

        /// <summary>
        /// Enum WBTC for value: WBTC
        /// </summary>
        [EnumMember(Value = "WBTC")]
        WBTC = 9,

        /// <summary>
        /// Enum SHIB for value: SHIB
        /// </summary>
        [EnumMember(Value = "SHIB")]
        SHIB = 10,

        /// <summary>
        /// Enum PEPE for value: PEPE
        /// </summary>
        [EnumMember(Value = "PEPE")]
        PEPE = 11,

        /// <summary>
        /// Enum LINK for value: LINK
        /// </summary>
        [EnumMember(Value = "LINK")]
        LINK = 12,

        /// <summary>
        /// Enum UNI for value: UNI
        /// </summary>
        [EnumMember(Value = "UNI")]
        UNI = 13,

        /// <summary>
        /// Enum AAVE for value: AAVE
        /// </summary>
        [EnumMember(Value = "AAVE")]
        AAVE = 14,

        /// <summary>
        /// Enum MKR for value: MKR
        /// </summary>
        [EnumMember(Value = "MKR")]
        MKR = 15
    }

}
