/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CryptoGate.Client.FileParameter;
using OpenAPIDateConverter = CryptoGate.Client.OpenAPIDateConverter;

namespace CryptoGate.Model
{
    /// <summary>
    /// One on-chain payment toward the transaction.
    /// </summary>
    [DataContract(Name = "PaymentSplit")]
    public partial class PaymentSplit : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentSplit" /> class.
        /// </summary>
        /// <param name="txid">On-chain transaction hash (blockchain id, NOT the CryptoGate transaction_id)..</param>
        /// <param name="amountCrypto">amountCrypto.</param>
        /// <param name="confirmations">confirmations.</param>
        /// <param name="status">status.</param>
        /// <param name="detectedAt">detectedAt.</param>
        /// <param name="confirmedAt">confirmedAt.</param>
        public PaymentSplit(string txid = default(string), decimal amountCrypto = default(decimal), int confirmations = default(int), string status = default(string), DateTime detectedAt = default(DateTime), DateTime? confirmedAt = default(DateTime?))
        {
            this.Txid = txid;
            this.AmountCrypto = amountCrypto;
            this.Confirmations = confirmations;
            this.Status = status;
            this.DetectedAt = detectedAt;
            this.ConfirmedAt = confirmedAt;
        }

        /// <summary>
        /// On-chain transaction hash (blockchain id, NOT the CryptoGate transaction_id).
        /// </summary>
        /// <value>On-chain transaction hash (blockchain id, NOT the CryptoGate transaction_id).</value>
        [DataMember(Name = "txid", EmitDefaultValue = false)]
        public string Txid { get; set; }

        /// <summary>
        /// Gets or Sets AmountCrypto
        /// </summary>
        [DataMember(Name = "amount_crypto", EmitDefaultValue = false)]
        public decimal AmountCrypto { get; set; }

        /// <summary>
        /// Gets or Sets Confirmations
        /// </summary>
        [DataMember(Name = "confirmations", EmitDefaultValue = false)]
        public int Confirmations { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets DetectedAt
        /// </summary>
        [DataMember(Name = "detected_at", EmitDefaultValue = false)]
        public DateTime DetectedAt { get; set; }

        /// <summary>
        /// Gets or Sets ConfirmedAt
        /// </summary>
        [DataMember(Name = "confirmed_at", EmitDefaultValue = true)]
        public DateTime? ConfirmedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentSplit {\n");
            sb.Append("  Txid: ").Append(Txid).Append("\n");
            sb.Append("  AmountCrypto: ").Append(AmountCrypto).Append("\n");
            sb.Append("  Confirmations: ").Append(Confirmations).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  DetectedAt: ").Append(DetectedAt).Append("\n");
            sb.Append("  ConfirmedAt: ").Append(ConfirmedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
