/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CryptoGate.Client.FileParameter;
using OpenAPIDateConverter = CryptoGate.Client.OpenAPIDateConverter;

namespace CryptoGate.Model
{
    /// <summary>
    /// The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
    /// </summary>
    [DataContract(Name = "Transaction")]
    public partial class Transaction : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public TransactionStatus Status { get; set; }
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Basic for value: basic
            /// </summary>
            [EnumMember(Value = "basic")]
            Basic = 1,

            /// <summary>
            /// Enum Detailed for value: detailed
            /// </summary>
            [EnumMember(Value = "detailed")]
            Detailed = 2
        }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// Gets or Sets Crypto
        /// </summary>
        [DataMember(Name = "crypto", IsRequired = true, EmitDefaultValue = true)]
        public CryptoSymbol Crypto { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyFiat
        /// </summary>
        [DataMember(Name = "currency_fiat", IsRequired = true, EmitDefaultValue = true)]
        public FiatCurrency CurrencyFiat { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Transaction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction" /> class.
        /// </summary>
        /// <param name="transactionId">transactionId (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="type">type.</param>
        /// <param name="crypto">crypto (required).</param>
        /// <param name="depositAddress">depositAddress.</param>
        /// <param name="amountCrypto">amountCrypto.</param>
        /// <param name="amountFiat">amountFiat (required).</param>
        /// <param name="amountUsd">amountUsd (required).</param>
        /// <param name="amountPaid">amountPaid.</param>
        /// <param name="amountRemaining">amountRemaining.</param>
        /// <param name="currencyFiat">currencyFiat (required).</param>
        /// <param name="fiatToUsdRate">fiatToUsdRate.</param>
        /// <param name="exchangeRate">USD per unit of crypto, locked at creation..</param>
        /// <param name="confirmationsRequired">confirmationsRequired.</param>
        /// <param name="paymentUrl">paymentUrl.</param>
        /// <param name="orderId">orderId.</param>
        /// <param name="customerEmail">customerEmail.</param>
        /// <param name="items">items.</param>
        /// <param name="payments">On-chain payments detected toward this transaction..</param>
        /// <param name="metadata">Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total)..</param>
        /// <param name="successUrl">successUrl.</param>
        /// <param name="cancelUrl">cancelUrl.</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt.</param>
        /// <param name="expiresAt">expiresAt (required).</param>
        public Transaction(string transactionId = default(string), TransactionStatus status = default(TransactionStatus), TypeEnum? type = default(TypeEnum?), CryptoSymbol crypto = default(CryptoSymbol), string depositAddress = default(string), decimal amountCrypto = default(decimal), decimal amountFiat = default(decimal), decimal amountUsd = default(decimal), decimal amountPaid = default(decimal), decimal amountRemaining = default(decimal), FiatCurrency currencyFiat = default(FiatCurrency), decimal fiatToUsdRate = default(decimal), decimal exchangeRate = default(decimal), int confirmationsRequired = default(int), string paymentUrl = default(string), string orderId = default(string), string customerEmail = default(string), List<LineItem> items = default(List<LineItem>), List<PaymentSplit> payments = default(List<PaymentSplit>), Dictionary<string, string> metadata = default(Dictionary<string, string>), string successUrl = default(string), string cancelUrl = default(string), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime), DateTime expiresAt = default(DateTime))
        {
            // to ensure "transactionId" is required (not null)
            if (transactionId == null)
            {
                throw new ArgumentNullException("transactionId is a required property for Transaction and cannot be null");
            }
            this.TransactionId = transactionId;
            this.Status = status;
            this.Crypto = crypto;
            this.AmountFiat = amountFiat;
            this.AmountUsd = amountUsd;
            this.CurrencyFiat = currencyFiat;
            this.CreatedAt = createdAt;
            this.ExpiresAt = expiresAt;
            this.Type = type;
            this.DepositAddress = depositAddress;
            this.AmountCrypto = amountCrypto;
            this.AmountPaid = amountPaid;
            this.AmountRemaining = amountRemaining;
            this.FiatToUsdRate = fiatToUsdRate;
            this.ExchangeRate = exchangeRate;
            this.ConfirmationsRequired = confirmationsRequired;
            this.PaymentUrl = paymentUrl;
            this.OrderId = orderId;
            this.CustomerEmail = customerEmail;
            this.Items = items;
            this.Payments = payments;
            this.Metadata = metadata;
            this.SuccessUrl = successUrl;
            this.CancelUrl = cancelUrl;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transaction_id", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets DepositAddress
        /// </summary>
        [DataMember(Name = "deposit_address", EmitDefaultValue = false)]
        public string DepositAddress { get; set; }

        /// <summary>
        /// Gets or Sets AmountCrypto
        /// </summary>
        [DataMember(Name = "amount_crypto", EmitDefaultValue = false)]
        public decimal AmountCrypto { get; set; }

        /// <summary>
        /// Gets or Sets AmountFiat
        /// </summary>
        [DataMember(Name = "amount_fiat", IsRequired = true, EmitDefaultValue = true)]
        public decimal AmountFiat { get; set; }

        /// <summary>
        /// Gets or Sets AmountUsd
        /// </summary>
        [DataMember(Name = "amount_usd", IsRequired = true, EmitDefaultValue = true)]
        public decimal AmountUsd { get; set; }

        /// <summary>
        /// Gets or Sets AmountPaid
        /// </summary>
        [DataMember(Name = "amount_paid", EmitDefaultValue = false)]
        public decimal AmountPaid { get; set; }

        /// <summary>
        /// Gets or Sets AmountRemaining
        /// </summary>
        [DataMember(Name = "amount_remaining", EmitDefaultValue = false)]
        public decimal AmountRemaining { get; set; }

        /// <summary>
        /// Gets or Sets FiatToUsdRate
        /// </summary>
        [DataMember(Name = "fiat_to_usd_rate", EmitDefaultValue = false)]
        public decimal FiatToUsdRate { get; set; }

        /// <summary>
        /// USD per unit of crypto, locked at creation.
        /// </summary>
        /// <value>USD per unit of crypto, locked at creation.</value>
        [DataMember(Name = "exchange_rate", EmitDefaultValue = false)]
        public decimal ExchangeRate { get; set; }

        /// <summary>
        /// Gets or Sets ConfirmationsRequired
        /// </summary>
        [DataMember(Name = "confirmations_required", EmitDefaultValue = false)]
        public int ConfirmationsRequired { get; set; }

        /// <summary>
        /// Gets or Sets PaymentUrl
        /// </summary>
        [DataMember(Name = "payment_url", EmitDefaultValue = false)]
        public string PaymentUrl { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name = "order_id", EmitDefaultValue = true)]
        public string OrderId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerEmail
        /// </summary>
        [DataMember(Name = "customer_email", EmitDefaultValue = true)]
        public string CustomerEmail { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", EmitDefaultValue = true)]
        public List<LineItem> Items { get; set; }

        /// <summary>
        /// On-chain payments detected toward this transaction.
        /// </summary>
        /// <value>On-chain payments detected toward this transaction.</value>
        [DataMember(Name = "payments", EmitDefaultValue = false)]
        public List<PaymentSplit> Payments { get; set; }

        /// <summary>
        /// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
        /// </summary>
        /// <value>Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Gets or Sets SuccessUrl
        /// </summary>
        [DataMember(Name = "success_url", EmitDefaultValue = true)]
        public string SuccessUrl { get; set; }

        /// <summary>
        /// Gets or Sets CancelUrl
        /// </summary>
        [DataMember(Name = "cancel_url", EmitDefaultValue = true)]
        public string CancelUrl { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name = "expires_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Transaction {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Crypto: ").Append(Crypto).Append("\n");
            sb.Append("  DepositAddress: ").Append(DepositAddress).Append("\n");
            sb.Append("  AmountCrypto: ").Append(AmountCrypto).Append("\n");
            sb.Append("  AmountFiat: ").Append(AmountFiat).Append("\n");
            sb.Append("  AmountUsd: ").Append(AmountUsd).Append("\n");
            sb.Append("  AmountPaid: ").Append(AmountPaid).Append("\n");
            sb.Append("  AmountRemaining: ").Append(AmountRemaining).Append("\n");
            sb.Append("  CurrencyFiat: ").Append(CurrencyFiat).Append("\n");
            sb.Append("  FiatToUsdRate: ").Append(FiatToUsdRate).Append("\n");
            sb.Append("  ExchangeRate: ").Append(ExchangeRate).Append("\n");
            sb.Append("  ConfirmationsRequired: ").Append(ConfirmationsRequired).Append("\n");
            sb.Append("  PaymentUrl: ").Append(PaymentUrl).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  CustomerEmail: ").Append(CustomerEmail).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Payments: ").Append(Payments).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  SuccessUrl: ").Append(SuccessUrl).Append("\n");
            sb.Append("  CancelUrl: ").Append(CancelUrl).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
