/*
 * CryptoGate API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = CryptoGate.Client.FileParameter;
using OpenAPIDateConverter = CryptoGate.Client.OpenAPIDateConverter;

namespace CryptoGate.Model
{
    /// <summary>
    /// Payment-event payload. AMOUNTS ARE STRINGS (e.g. \&quot;100.00\&quot;, \&quot;0.00109462\&quot;) to preserve decimal precision — parse before arithmetic. 
    /// </summary>
    [DataContract(Name = "WebhookPayload")]
    public partial class WebhookPayload : IValidatableObject
    {
        /// <summary>
        /// Defines Event
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventEnum
        {
            /// <summary>
            /// Enum Created for value: payment.created
            /// </summary>
            [EnumMember(Value = "payment.created")]
            Created = 1,

            /// <summary>
            /// Enum Pending for value: payment.pending
            /// </summary>
            [EnumMember(Value = "payment.pending")]
            Pending = 2,

            /// <summary>
            /// Enum Completed for value: payment.completed
            /// </summary>
            [EnumMember(Value = "payment.completed")]
            Completed = 3,

            /// <summary>
            /// Enum Overpaid for value: payment.overpaid
            /// </summary>
            [EnumMember(Value = "payment.overpaid")]
            Overpaid = 4,

            /// <summary>
            /// Enum Partial for value: payment.partial
            /// </summary>
            [EnumMember(Value = "payment.partial")]
            Partial = 5,

            /// <summary>
            /// Enum Expired for value: payment.expired
            /// </summary>
            [EnumMember(Value = "payment.expired")]
            Expired = 6,

            /// <summary>
            /// Enum Failed for value: payment.failed
            /// </summary>
            [EnumMember(Value = "payment.failed")]
            Failed = 7
        }


        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public EventEnum Event { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public TransactionStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyCrypto
        /// </summary>
        [DataMember(Name = "currency_crypto", EmitDefaultValue = false)]
        public CryptoSymbol? CurrencyCrypto { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyFiat
        /// </summary>
        [DataMember(Name = "currency_fiat", EmitDefaultValue = false)]
        public FiatCurrency? CurrencyFiat { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookPayload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebhookPayload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookPayload" /> class.
        /// </summary>
        /// <param name="varEvent">varEvent (required).</param>
        /// <param name="timestamp">timestamp (required).</param>
        /// <param name="transactionId">transactionId (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="currencyCrypto">currencyCrypto.</param>
        /// <param name="currencyFiat">currencyFiat.</param>
        /// <param name="amountFiat">Decimal string..</param>
        /// <param name="amountUsd">Decimal string..</param>
        /// <param name="amountCrypto">Decimal string..</param>
        /// <param name="orderId">orderId.</param>
        /// <param name="receiptUrl">Present on completed/overpaid..</param>
        /// <param name="metadata">Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total)..</param>
        public WebhookPayload(EventEnum varEvent = default(EventEnum), DateTime timestamp = default(DateTime), string transactionId = default(string), TransactionStatus status = default(TransactionStatus), CryptoSymbol? currencyCrypto = default(CryptoSymbol?), FiatCurrency? currencyFiat = default(FiatCurrency?), string amountFiat = default(string), string amountUsd = default(string), string amountCrypto = default(string), string orderId = default(string), string receiptUrl = default(string), Dictionary<string, string> metadata = default(Dictionary<string, string>))
        {
            this.Event = varEvent;
            this.Timestamp = timestamp;
            // to ensure "transactionId" is required (not null)
            if (transactionId == null)
            {
                throw new ArgumentNullException("transactionId is a required property for WebhookPayload and cannot be null");
            }
            this.TransactionId = transactionId;
            this.Status = status;
            this.CurrencyCrypto = currencyCrypto;
            this.CurrencyFiat = currencyFiat;
            this.AmountFiat = amountFiat;
            this.AmountUsd = amountUsd;
            this.AmountCrypto = amountCrypto;
            this.OrderId = orderId;
            this.ReceiptUrl = receiptUrl;
            this.Metadata = metadata;
        }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transaction_id", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Decimal string.
        /// </summary>
        /// <value>Decimal string.</value>
        [DataMember(Name = "amount_fiat", EmitDefaultValue = false)]
        public string AmountFiat { get; set; }

        /// <summary>
        /// Decimal string.
        /// </summary>
        /// <value>Decimal string.</value>
        [DataMember(Name = "amount_usd", EmitDefaultValue = false)]
        public string AmountUsd { get; set; }

        /// <summary>
        /// Decimal string.
        /// </summary>
        /// <value>Decimal string.</value>
        [DataMember(Name = "amount_crypto", EmitDefaultValue = false)]
        public string AmountCrypto { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name = "order_id", EmitDefaultValue = true)]
        public string OrderId { get; set; }

        /// <summary>
        /// Present on completed/overpaid.
        /// </summary>
        /// <value>Present on completed/overpaid.</value>
        [DataMember(Name = "receipt_url", EmitDefaultValue = true)]
        public string ReceiptUrl { get; set; }

        /// <summary>
        /// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
        /// </summary>
        /// <value>Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookPayload {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CurrencyCrypto: ").Append(CurrencyCrypto).Append("\n");
            sb.Append("  CurrencyFiat: ").Append(CurrencyFiat).Append("\n");
            sb.Append("  AmountFiat: ").Append(AmountFiat).Append("\n");
            sb.Append("  AmountUsd: ").Append(AmountUsd).Append("\n");
            sb.Append("  AmountCrypto: ").Append(AmountCrypto).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  ReceiptUrl: ").Append(ReceiptUrl).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
