/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GriffNode.SDK.Model;
using GriffNode.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GriffNode.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        public TransactionTests()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Fact]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Transaction
            //Assert.IsType<Transaction>(instance);
        }

        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Crypto'
        /// </summary>
        [Fact]
        public void CryptoTest()
        {
            // TODO unit test for the property 'Crypto'
        }

        /// <summary>
        /// Test the property 'DepositAddress'
        /// </summary>
        [Fact]
        public void DepositAddressTest()
        {
            // TODO unit test for the property 'DepositAddress'
        }

        /// <summary>
        /// Test the property 'AmountCrypto'
        /// </summary>
        [Fact]
        public void AmountCryptoTest()
        {
            // TODO unit test for the property 'AmountCrypto'
        }

        /// <summary>
        /// Test the property 'AmountFiat'
        /// </summary>
        [Fact]
        public void AmountFiatTest()
        {
            // TODO unit test for the property 'AmountFiat'
        }

        /// <summary>
        /// Test the property 'AmountUsd'
        /// </summary>
        [Fact]
        public void AmountUsdTest()
        {
            // TODO unit test for the property 'AmountUsd'
        }

        /// <summary>
        /// Test the property 'AmountPaid'
        /// </summary>
        [Fact]
        public void AmountPaidTest()
        {
            // TODO unit test for the property 'AmountPaid'
        }

        /// <summary>
        /// Test the property 'AmountRemaining'
        /// </summary>
        [Fact]
        public void AmountRemainingTest()
        {
            // TODO unit test for the property 'AmountRemaining'
        }

        /// <summary>
        /// Test the property 'CurrencyFiat'
        /// </summary>
        [Fact]
        public void CurrencyFiatTest()
        {
            // TODO unit test for the property 'CurrencyFiat'
        }

        /// <summary>
        /// Test the property 'FiatToUsdRate'
        /// </summary>
        [Fact]
        public void FiatToUsdRateTest()
        {
            // TODO unit test for the property 'FiatToUsdRate'
        }

        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Fact]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }

        /// <summary>
        /// Test the property 'ConfirmationsRequired'
        /// </summary>
        [Fact]
        public void ConfirmationsRequiredTest()
        {
            // TODO unit test for the property 'ConfirmationsRequired'
        }

        /// <summary>
        /// Test the property 'PaymentUrl'
        /// </summary>
        [Fact]
        public void PaymentUrlTest()
        {
            // TODO unit test for the property 'PaymentUrl'
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }

        /// <summary>
        /// Test the property 'CustomerEmail'
        /// </summary>
        [Fact]
        public void CustomerEmailTest()
        {
            // TODO unit test for the property 'CustomerEmail'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Payments'
        /// </summary>
        [Fact]
        public void PaymentsTest()
        {
            // TODO unit test for the property 'Payments'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'SuccessUrl'
        /// </summary>
        [Fact]
        public void SuccessUrlTest()
        {
            // TODO unit test for the property 'SuccessUrl'
        }

        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
    }
}
