/*
 * GriffNode API
 *
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GriffNode.SDK.Model;
using GriffNode.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GriffNode.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionStatus
        //private TransactionStatus instance;

        public TransactionStatusTests()
        {
            // TODO uncomment below to create an instance of TransactionStatus
            //instance = new TransactionStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionStatus
        /// </summary>
        [Fact]
        public void TransactionStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionStatus
            //Assert.IsType<TransactionStatus>(instance);
        }
    }
}
